import type { Metadata } from "next";
import Link from "next/link";
import { HelpCircle, Mail } from "lucide-react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export const metadata: Metadata = {
  title: "FAQ - Smart Invoice Tool | Frequently Asked Questions",
  description: "Find answers to frequently asked questions about Smart Invoice Tool, our free invoice generator, features, and usage.",
  keywords: "FAQ, frequently asked questions, smart invoice tool help, invoice generator FAQ, billing questions",
  openGraph: {
    title: "FAQ - Smart Invoice Tool | Frequently Asked Questions",
    description: "Find answers to frequently asked questions about Smart Invoice Tool and our free invoice generator.",
    url: "https://smartinvoicetool.com/faq",
  },
  alternates: {
    canonical: "/faq",
  },
};

export default function FAQ() {
  const faqCategories = [
    {
      title: "General Questions",
      items: [
        {
          question: "Is Smart Invoice Tool completely free?",
          answer: "Yes, Smart Invoice Tool is 100% free to use. There are no hidden costs, subscription fees, or premium tiers. You can create unlimited invoices, export to PDF, and use all features without any charges."
        },
        {
          question: "Do I need to create an account or register?",
          answer: "No registration is required. You can start creating professional invoices immediately without signing up or providing any personal information. Just visit our website and start using the tool."
        },
        {
          question: "Is my data safe and private?",
          answer: "Absolutely. All your invoice data is processed locally in your browser and never leaves your device. We don't store, collect, or have access to any of your business information or invoice data."
        }
      ]
    },
    {
      title: "Features & Usage",
      items: [
        {
          question: "What currencies are supported?",
          answer: "We support 10+ major currencies including USD, EUR, GBP, LKR (Sri Lankan Rupee), INR, JPY, CAD, AUD, CHF, and CNY. You can select your preferred currency from the dropdown menu."
        },
        {
          question: "Can I add my company logo to invoices?",
          answer: "Yes, you can easily upload your company logo by clicking the \"Upload Logo\" button. The logo will appear on both the preview and the PDF export of your invoice."
        },
        {
          question: "How do I download my invoice as PDF?",
          answer: "Once you've created your invoice, simply click the \"Download PDF\" button. The PDF will be generated instantly and downloaded to your device with high-quality formatting."
        },
        {
          question: "Can I customize the invoice template?",
          answer: "Yes, you can customize various elements including colors, fonts, and layout. You can also add your company details, client information, and item descriptions."
        }
      ]
    },
    {
      title: "Technical & Legal",
      items: [
        {
          question: "What browsers are supported?",
          answer: "Smart Invoice Tool works on all modern browsers including Chrome, Firefox, Safari, and Edge. For the best experience, we recommend using the latest version of your browser."
        },
        {
          question: "Is there a mobile app?",
          answer: "Currently, we don't have a dedicated mobile app, but our website is fully responsive and works great on mobile devices and tablets through your mobile browser."
        },
        {
          question: "Are the generated invoices legally valid?",
          answer: "The invoices generated by our tool are professionally formatted and contain all standard elements. However, you should consult with a tax professional or legal advisor in your jurisdiction to ensure compliance with local regulations."
        }
      ]
    }
  ];

  return (
    <main className="min-h-screen bg-slate-50">
      {/* Hero Section */}
      <section className="bg-white border-b border-slate-200 py-16 px-4">
        <div className="container mx-auto max-w-4xl text-center">
          <div className="inline-flex items-center justify-center p-3 bg-blue-100 rounded-full mb-6">
            <HelpCircle className="w-8 h-8 text-blue-600" />
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-slate-900 mb-6">
            Frequently Asked Questions
          </h1>
          <p className="text-xl text-slate-600 max-w-2xl mx-auto">
            Everything you need to know about Smart Invoice Tool. Can&apos;t find the answer you&apos;re looking for? Feel free to contact us.
          </p>
        </div>
      </section>

      {/* FAQ Content */}
      <section className="py-16 px-4">
        <div className="container mx-auto max-w-3xl">
          <div className="space-y-12">
            {faqCategories.map((category, idx) => (
              <div key={idx} className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6 md:p-8">
                <h2 className="text-2xl font-bold text-slate-900 mb-6">{category.title}</h2>
                <Accordion type="single" collapsible className="w-full">
                  {category.items.map((item, itemIdx) => (
                    <AccordionItem key={itemIdx} value={`item-${idx}-${itemIdx}`}>
                      <AccordionTrigger className="text-left font-medium text-slate-900 hover:text-blue-600 hover:no-underline">
                        {item.question}
                      </AccordionTrigger>
                      <AccordionContent className="text-slate-600 leading-relaxed">
                        {item.answer}
                      </AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              </div>
            ))}
          </div>

          {/* Contact CTA */}
          <div className="mt-16 bg-blue-600 rounded-2xl p-8 md:p-12 text-center text-white">
            <h3 className="text-2xl font-bold mb-4">Still have questions?</h3>
            <p className="text-blue-100 mb-8 max-w-xl mx-auto">
              Can&apos;t find the answer you&apos;re looking for? Please send us a message and we&apos;ll be happy to help you.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link 
                href="/contact" 
                className="inline-flex items-center justify-center gap-2 bg-white text-blue-600 font-semibold py-3 px-6 rounded-lg hover:bg-blue-50 transition-colors"
              >
                <Mail className="w-5 h-5" />
                Contact Support
              </Link>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
